// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC3() {
    // Test name: TC3
    // Step # | name | target | value
    // 1 | open | https://www.phptravels.net/account/dashboard | 
    driver.get("https://www.phptravels.net/account/dashboard");
    // 2 | setWindowSize | 830x1039 | 
    driver.manage().window().setSize(new Dimension(830, 1039));
    // 3 | click | css=.la-bars | 
    driver.findElement(By.cssSelector(".la-bars")).click();
    // 4 | click | linkText=Tours | 
    driver.findElement(By.linkText("Tours")).click();
    // 5 | click | css=.col-lg-4:nth-child(4) .card-img | 
    driver.findElement(By.cssSelector(".col-lg-4:nth-child(4) .card-img")).click();
    // 6 | click | linkText=Inclusions | 
    driver.findElement(By.linkText("Inclusions")).click();
    // 7 | click | css=.ladda-label | 
    driver.findElement(By.cssSelector(".ladda-label")).click();
    // 8 | click | name=nationality | 
    driver.findElement(By.name("nationality")).click();
    // 9 | select | name=nationality | label=Hungary
    {
      WebElement dropdown = driver.findElement(By.name("nationality"));
      dropdown.findElement(By.xpath("//option[. = 'Hungary']")).click();
    }
    // 10 | click | name=firstname_1 | 
    driver.findElement(By.name("firstname_1")).click();
    // 11 | type | name=firstname_1 | Gal
    driver.findElement(By.name("firstname_1")).sendKeys("Gal");
    // 12 | click | name=lastname_1 | 
    driver.findElement(By.name("lastname_1")).click();
    // 13 | click | name=lastname_1 | 
    driver.findElement(By.name("lastname_1")).click();
    // 14 | type | name=lastname_1 | Csa
    driver.findElement(By.name("lastname_1")).sendKeys("Csa");
    // 15 | click | id=gateway_pay-later | 
    driver.findElement(By.id("gateway_pay-later")).click();
    // 16 | click | css=.custom-checkbox > label | 
    driver.findElement(By.cssSelector(".custom-checkbox > label")).click();
    // 17 | click | id=booking | 
    driver.findElement(By.id("booking")).click();
  }
}
